# -*- coding: utf-8 -*-
"""Audio Data Preparation and Augmentation in Tensorflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPp5d0ki0bh99b1TUO73A9sVvFp8DL-O
"""

!pip install tensorflow-io

#importing necessary libraries
import tensorflow as tf
import tensorflow_io as tfio
#loading and reading the audio file.
audio_data = tfio.audio.AudioIOTensor('/content/CantinaBand3.wav')
print(audio_data)
print(audio_data.shape)
print(audio_data.rate)

#perform slicing
audio_sl = audio_data[6:]
print('Shape After Slicing :',audio_sl.shape)

#last dimension is ignored.
audio_t = tf.squeeze(audio_sl, axis=[-1])
print('Shape After squeezing:',audio_t.shape)

#to play the audio,
from IPython.display import Audio
Audio(audio_t.numpy(), rate=audio_data.rate.numpy())

# convert tensor to float datatype,.
tensor = tf.cast(audio_t, tf.float32) / 32767.0
print(tensor)

#plot the graph.
import matplotlib.pyplot as plt
plt.figure()
plt.plot(tensor.numpy())
plt.show()

# Trim silence from the beginning and end of the audio signal
trimed = tfio.audio.trim(tensor,
						axis=0,
						epsilon=0.2)
print('Trimmed :',trimed)

#Mention the stating and ending limit
start = trimed[0]
stop = trimed[1]
print("START:{},\nSTOP :{}".format(start.numpy(),
								stop.numpy()))
trimmed_audio = tensor[start:stop]
print('Trimmed Audio shape:',trimmed_audio.shape)

plt.figure()
plt.plot(trimmed_audio.numpy())
#to play the audio,
Audio(trimmed_audio.numpy(),
	rate=audio_data.rate.numpy())

#Apply a fade-in and fade_out effect with a duration
audio_fade = tfio.audio.fade(trimmed_audio,
							fade_in=1000,
							fade_out=2000,
							mode="logarithmic")

plt.figure()
#plotting the faded audio.
plt.plot(audio_fade.numpy())
#to plat the audio
Audio(audio_fade.numpy(),
	rate=audio_data.rate.numpy())

# Convert to spectrogram
spectrogram = tfio.audio.spectrogram(audio_fade,
									nfft=512,
									window=512,
									stride=512)

plt.figure()
#plotting spectrogram
plt.imshow(tf.math.log(spectrogram).numpy())
plt.show()

# Convert spectrogram to mel spectrogram with 250 mel bands
spectrogram_mel = tfio.audio.melscale(spectrogram, rate=16000, mels=250, fmin=0, fmax=7000)
plt.figure()
plt.imshow(tf.math.log(spectrogram_mel).numpy())

#Convert spectrogram to decibel scale with top_db=70
spectrogram_dbscale = tfio.audio.dbscale(spectrogram_mel, top_db=70)
plt.figure()

plt.imshow(spectrogram_dbscale.numpy())
plt.show()

# Apply frequency masking with
# a max mask width of 100 frequency bins
spec_freq_mask = tfio.audio.freq_mask(spectrogram_dbscale, param=100)
plt.figure()
plt.imshow(spec_freq_mask.numpy())
plt.show()

# Apply time masking with
# a max mask width of 50 time steps
audio_time_masked = tfio.audio.time_mask(spectrogram_dbscale,
										param=50)
plt.figure()
plt.imshow(audio_time_masked.numpy())
plt.show()